apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scalper
resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  # - secret.yaml   # create from secret.example.yaml, keep out of git
